// Generated by the final SEO build step, after canonical-page validation.
// Routing Middleware supports Hobby, unlike Vercel Bulk Redirects.
import redirects from "./.vercel/stoppin-venue-redirects.json" with { type: "json" };

export const config = { matcher: "/restaurants-pres/:path*" };

const destinations = new Map(redirects.map(({ source, destination }) => [source, destination]));

export default function middleware(request) {
  const url = new URL(request.url);
  const destination = destinations.get(url.pathname);
  if (!destination) return;

  // Exact, case-sensitive lookup; preserve the query string and same origin.
  url.pathname = destination;
  return Response.redirect(url, 301);
}
