BEGIN;

-- TOK Intelligence Suite: Campaign Studio, Customer Memory,
-- Support Resolution and Guardian.
-- Additive only: no existing table, policy or historical migration is altered.

CREATE TABLE IF NOT EXISTS public.campaign_studio_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  restaurant_id uuid NOT NULL REFERENCES public.restaurants(id) ON DELETE CASCADE,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  idempotency_key text NOT NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN ('draft', 'approved', 'launched', 'paused', 'stopped', 'failed')),
  objective text NOT NULL DEFAULT '',
  request_prompt text NOT NULL DEFAULT '',
  plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  guardrails jsonb NOT NULL DEFAULT '{}'::jsonb,
  projected_metrics jsonb NOT NULL DEFAULT '{}'::jsonb,
  approval_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at timestamptz,
  campaign_id uuid REFERENCES public.ad_campaigns(id) ON DELETE SET NULL,
  launched_at timestamptz,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT campaign_studio_runs_idempotency_not_blank
    CHECK (btrim(idempotency_key) <> ''),
  CONSTRAINT campaign_studio_runs_prompt_length
    CHECK (char_length(request_prompt) <= 4000),
  CONSTRAINT campaign_studio_runs_objective_length
    CHECK (char_length(objective) <= 240)
);

CREATE UNIQUE INDEX IF NOT EXISTS campaign_studio_runs_restaurant_idempotency_uidx
  ON public.campaign_studio_runs (restaurant_id, idempotency_key);
CREATE INDEX IF NOT EXISTS campaign_studio_runs_restaurant_created_idx
  ON public.campaign_studio_runs (restaurant_id, created_at DESC);
CREATE INDEX IF NOT EXISTS campaign_studio_runs_status_created_idx
  ON public.campaign_studio_runs (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.customer_memory_items (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  memory_key text NOT NULL,
  label text NOT NULL,
  category text NOT NULL
    CHECK (category IN ('preference', 'context', 'accessibility', 'dietary', 'budget', 'location', 'service')),
  value jsonb NOT NULL DEFAULT '{}'::jsonb,
  source text NOT NULL
    CHECK (source IN ('explicit', 'inferred')),
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'active', 'rejected', 'deleted')),
  confidence numeric(5,4) NOT NULL DEFAULT 1
    CHECK (confidence >= 0 AND confidence <= 1),
  sensitivity text NOT NULL DEFAULT 'standard'
    CHECK (sensitivity IN ('standard', 'sensitive')),
  evidence jsonb NOT NULL DEFAULT '{}'::jsonb,
  expires_at timestamptz,
  confirmed_at timestamptz,
  rejected_at timestamptz,
  deleted_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT customer_memory_items_key_not_blank
    CHECK (btrim(memory_key) <> ''),
  CONSTRAINT customer_memory_items_label_not_blank
    CHECK (btrim(label) <> ''),
  CONSTRAINT customer_memory_items_key_length
    CHECK (char_length(memory_key) <= 100),
  CONSTRAINT customer_memory_items_label_length
    CHECK (char_length(label) <= 160)
);

CREATE UNIQUE INDEX IF NOT EXISTS customer_memory_items_user_key_uidx
  ON public.customer_memory_items (user_id, memory_key);
CREATE INDEX IF NOT EXISTS customer_memory_items_user_status_idx
  ON public.customer_memory_items (user_id, status, updated_at DESC);
CREATE INDEX IF NOT EXISTS customer_memory_items_expiry_idx
  ON public.customer_memory_items (expires_at)
  WHERE expires_at IS NOT NULL AND status IN ('pending', 'active');

CREATE TABLE IF NOT EXISTS public.customer_memory_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  item_id uuid REFERENCES public.customer_memory_items(id) ON DELETE SET NULL,
  user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  actor_user_id uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  event_type text NOT NULL
    CHECK (event_type IN (
      'created',
      'updated',
      'confirmed',
      'rejected',
      'deleted',
      'cleared',
      'inference_generated',
      'exported',
      'consent_blocked'
    )),
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS customer_memory_events_user_created_idx
  ON public.customer_memory_events (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS customer_memory_events_item_created_idx
  ON public.customer_memory_events (item_id, created_at DESC)
  WHERE item_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.support_resolution_runs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id uuid NOT NULL REFERENCES public.support_incidents(id) ON DELETE CASCADE,
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'draft'
    CHECK (status IN (
      'draft',
      'awaiting_approval',
      'approved',
      'executing',
      'completed',
      'rejected',
      'failed'
    )),
  title text NOT NULL DEFAULT '',
  executive_summary text NOT NULL DEFAULT '',
  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  customer_safe_summary text NOT NULL DEFAULT '',
  risk_level text NOT NULL DEFAULT 'medium'
    CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
  confidence numeric(5,4)
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at timestamptz,
  completed_at timestamptz,
  last_error text,
  model text,
  usage jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS support_resolution_runs_incident_created_idx
  ON public.support_resolution_runs (incident_id, created_at DESC);
CREATE INDEX IF NOT EXISTS support_resolution_runs_status_created_idx
  ON public.support_resolution_runs (status, created_at DESC);

CREATE TABLE IF NOT EXISTS public.support_resolution_actions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  run_id uuid NOT NULL REFERENCES public.support_resolution_runs(id) ON DELETE CASCADE,
  incident_id uuid NOT NULL REFERENCES public.support_incidents(id) ON DELETE CASCADE,
  idempotency_key text NOT NULL,
  action_type text NOT NULL
    CHECK (action_type IN (
      'add_internal_note',
      'resend_booking_confirmation',
      'resend_order_receipt',
      'request_restaurant_response',
      'set_waiting_customer',
      'set_waiting_restaurant',
      'close_incident',
      'request_refund',
      'grant_credit',
      'manual_review'
    )),
  label text NOT NULL DEFAULT '',
  reason text NOT NULL DEFAULT '',
  arguments jsonb NOT NULL DEFAULT '{}'::jsonb,
  requires_approval boolean NOT NULL DEFAULT true,
  status text NOT NULL DEFAULT 'proposed'
    CHECK (status IN (
      'proposed',
      'approved',
      'executing',
      'completed',
      'rejected',
      'manual_required',
      'failed'
    )),
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  executed_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  approved_at timestamptz,
  executed_at timestamptz,
  result jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT support_resolution_actions_idempotency_not_blank
    CHECK (btrim(idempotency_key) <> '')
);

CREATE UNIQUE INDEX IF NOT EXISTS support_resolution_actions_idempotency_uidx
  ON public.support_resolution_actions (idempotency_key);
CREATE INDEX IF NOT EXISTS support_resolution_actions_run_status_idx
  ON public.support_resolution_actions (run_id, status, created_at);
CREATE INDEX IF NOT EXISTS support_resolution_actions_incident_created_idx
  ON public.support_resolution_actions (incident_id, created_at DESC);

CREATE TABLE IF NOT EXISTS public.ops_guardian_assessments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id uuid NOT NULL REFERENCES public.ops_incidents(id) ON DELETE CASCADE,
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'completed'
    CHECK (status IN ('completed', 'failed')),
  severity text NOT NULL DEFAULT 'medium'
    CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  risk_level text NOT NULL DEFAULT 'medium'
    CHECK (risk_level IN ('low', 'medium', 'high', 'critical')),
  confidence numeric(5,4)
    CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  assessment jsonb NOT NULL DEFAULT '{}'::jsonb,
  model text,
  usage jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ops_guardian_assessments_incident_created_idx
  ON public.ops_guardian_assessments (incident_id, created_at DESC);
CREATE INDEX IF NOT EXISTS ops_guardian_assessments_severity_created_idx
  ON public.ops_guardian_assessments (severity, created_at DESC);

CREATE TABLE IF NOT EXISTS public.ops_guardian_verifications (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  incident_id uuid NOT NULL REFERENCES public.ops_incidents(id) ON DELETE CASCADE,
  requested_by uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'healthy', 'degraded', 'failed')),
  function_name text,
  observation_started_at timestamptz NOT NULL DEFAULT now(),
  observation_ended_at timestamptz,
  checks jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS ops_guardian_verifications_incident_created_idx
  ON public.ops_guardian_verifications (incident_id, created_at DESC);

ALTER TABLE public.campaign_studio_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_memory_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.customer_memory_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_resolution_runs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.support_resolution_actions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_guardian_assessments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_guardian_verifications ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.campaign_studio_runs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.customer_memory_items FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.customer_memory_events FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_resolution_runs FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.support_resolution_actions FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.ops_guardian_assessments FROM PUBLIC, anon, authenticated;
REVOKE ALL ON public.ops_guardian_verifications FROM PUBLIC, anon, authenticated;

GRANT SELECT ON public.campaign_studio_runs TO authenticated;
GRANT SELECT ON public.customer_memory_items TO authenticated;
GRANT SELECT ON public.customer_memory_events TO authenticated;
GRANT SELECT ON public.support_resolution_runs TO authenticated;
GRANT SELECT ON public.support_resolution_actions TO authenticated;
GRANT SELECT ON public.ops_guardian_assessments TO authenticated;
GRANT SELECT ON public.ops_guardian_verifications TO authenticated;

GRANT ALL ON public.campaign_studio_runs TO service_role;
GRANT ALL ON public.customer_memory_items TO service_role;
GRANT ALL ON public.customer_memory_events TO service_role;
GRANT ALL ON public.support_resolution_runs TO service_role;
GRANT ALL ON public.support_resolution_actions TO service_role;
GRANT ALL ON public.ops_guardian_assessments TO service_role;
GRANT ALL ON public.ops_guardian_verifications TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.customer_memory_events_id_seq TO service_role;

DROP POLICY IF EXISTS "Restaurant members can read campaign studio runs"
  ON public.campaign_studio_runs;
CREATE POLICY "Restaurant members can read campaign studio runs"
  ON public.campaign_studio_runs
  FOR SELECT
  TO authenticated
  USING (
    public.auth_is_admin()
    OR public.auth_owns_restaurant(restaurant_id)
  );

DROP POLICY IF EXISTS "Users can read own customer memory"
  ON public.customer_memory_items;
CREATE POLICY "Users can read own customer memory"
  ON public.customer_memory_items
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Users can read own customer memory events"
  ON public.customer_memory_events;
CREATE POLICY "Users can read own customer memory events"
  ON public.customer_memory_events
  FOR SELECT
  TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "Admins can read support resolution runs"
  ON public.support_resolution_runs;
CREATE POLICY "Admins can read support resolution runs"
  ON public.support_resolution_runs
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

DROP POLICY IF EXISTS "Admins can read support resolution actions"
  ON public.support_resolution_actions;
CREATE POLICY "Admins can read support resolution actions"
  ON public.support_resolution_actions
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

DROP POLICY IF EXISTS "Admins can read guardian assessments"
  ON public.ops_guardian_assessments;
CREATE POLICY "Admins can read guardian assessments"
  ON public.ops_guardian_assessments
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

DROP POLICY IF EXISTS "Admins can read guardian verifications"
  ON public.ops_guardian_verifications;
CREATE POLICY "Admins can read guardian verifications"
  ON public.ops_guardian_verifications
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

INSERT INTO public.feature_flags (name, label, description, is_active)
VALUES
  (
    'dashboard-campaign-studio',
    'TOK Campaign Studio',
    'Studio IA de planification, simulation et lancement contrôlé des campagnes restaurateur.',
    true
  ),
  (
    'customer-memory',
    'TOK Customer Memory',
    'Mémoire explicite et consentie des préférences client, consultable et révocable.',
    true
  ),
  (
    'admin-support-resolution',
    'TOK Support & Resolution',
    'Diagnostic IA et exécution contrôlée des actions de résolution support.',
    true
  ),
  (
    'admin-guardian',
    'TOK Guardian',
    'Tour de contrôle IA des incidents, causes probables et vérifications post-déploiement.',
    true
  )
ON CONFLICT (name) DO UPDATE
SET
  label = EXCLUDED.label,
  description = EXCLUDED.description,
  is_active = EXCLUDED.is_active,
  updated_at = now();

COMMENT ON TABLE public.campaign_studio_runs IS
  'Versioned AI campaign plans. Actual campaign writes remain delegated to campaign-portal.';
COMMENT ON TABLE public.customer_memory_items IS
  'Consent-gated customer preferences. Sensitive inference is forbidden; users retain full control.';
COMMENT ON TABLE public.customer_memory_events IS
  'Append-only audit trail for customer memory lifecycle and consent blocks.';
COMMENT ON TABLE public.support_resolution_runs IS
  'Admin-only AI diagnosis snapshots for support incidents.';
COMMENT ON TABLE public.support_resolution_actions IS
  'Audited, idempotent resolution actions. Financial actions always remain manual.';
COMMENT ON TABLE public.ops_guardian_assessments IS
  'Admin-only Guardian assessments attached to existing ops_incidents.';
COMMENT ON TABLE public.ops_guardian_verifications IS
  'Post-change observation records; incidents are not resolved solely because a PR exists.';

COMMIT;
