-- Keep admin and restaurant accounting aligned on the same net base:
-- gross paid amount plus TOK-covered Miamz, minus refunds already applied.
-- This prevents invoices generated by SQL from drifting from frontend ledgers.

CREATE OR REPLACE FUNCTION public.generate_restaurant_payout_invoice(
  p_restaurant_id uuid,
  p_month text DEFAULT NULL::text
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  inv_id uuid;
  next_num integer;
  rev numeric := 0;
  res_rev numeric := 0;
  payout_amount numeric := 0;
  tva_rate numeric := 0.077;
  unpaid_orders_count integer := 0;
  unpaid_reservations_count integer := 0;
  order_min_date timestamptz;
  order_max_date timestamptz;
  reservation_min_date timestamptz;
  reservation_max_date timestamptz;
  min_date timestamptz;
  max_date timestamptz;
  v_target date := NULLIF(trim(COALESCE(p_month, '')), '')::date;
  v_has_month boolean := v_target IS NOT NULL;
  inv_period_s date;
  inv_period_e date;
BEGIN
  IF NOT (auth.role() = 'service_role' OR public.auth_is_admin()) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF v_has_month THEN
    inv_period_s := date_trunc('month', v_target)::date;
    inv_period_e := (inv_period_s + interval '1 month - 1 day')::date;
  END IF;

  SELECT
    COUNT(*),
    COALESCE(SUM(net_amount), 0),
    MIN(created_at),
    MAX(created_at)
  INTO unpaid_orders_count, rev, order_min_date, order_max_date
  FROM (
    SELECT
      o.created_at,
      GREATEST(
        COALESCE(o.total_amount, 0)
        + COALESCE((o.metadata ->> 'points_discount_amount')::numeric, (o.metadata ->> 'points_discount')::numeric, 0)
        - COALESCE(o.refunded_amount_chf, 0),
        0
      ) AS net_amount
    FROM public.orders o
    WHERE o.restaurant_id = p_restaurant_id
      AND o.restaurant_invoice_id IS NULL
      AND lower(COALESCE(o.status, '')) NOT IN ('cancelled', 'refused', 'payment_failed', 'pending')
      AND lower(COALESCE(o.payment_status, '')) IN ('paid', 'captured')
      AND (
        NOT v_has_month
        OR (
          o.created_at >= inv_period_s::timestamptz
          AND o.created_at < (inv_period_e + 1)::timestamptz
        )
      )
  ) AS eligible_orders
  WHERE net_amount > 0;

  SELECT
    COUNT(*),
    COALESCE(SUM(net_amount), 0),
    MIN(created_at),
    MAX(created_at)
  INTO unpaid_reservations_count, res_rev, reservation_min_date, reservation_max_date
  FROM (
    SELECT
      COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) AS created_at,
      GREATEST(
        COALESCE(r.total_amount, 0) - COALESCE(r.refunded_amount_chf, 0),
        0
      ) AS net_amount
    FROM public.reservations r
    WHERE r.restaurant_id = p_restaurant_id
      AND r.restaurant_invoice_id IS NULL
      AND lower(COALESCE(r.status, '')) NOT IN ('cancelled', 'no_show', 'pending')
      AND COALESCE(r.total_amount, 0) > 0
      AND (
        NOT v_has_month
        OR (
          COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) >= inv_period_s::timestamptz
          AND COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) < (inv_period_e + 1)::timestamptz
        )
      )
  ) AS eligible_reservations
  WHERE net_amount > 0;

  IF unpaid_orders_count = 0 AND unpaid_reservations_count = 0 THEN
    RETURN 0;
  END IF;

  min_date := CASE
    WHEN order_min_date IS NULL THEN reservation_min_date
    WHEN reservation_min_date IS NULL THEN order_min_date
    ELSE LEAST(order_min_date, reservation_min_date)
  END;
  max_date := CASE
    WHEN order_max_date IS NULL THEN reservation_max_date
    WHEN reservation_max_date IS NULL THEN order_max_date
    ELSE GREATEST(order_max_date, reservation_max_date)
  END;

  payout_amount := ROUND((rev + res_rev) * 0.90, 2);

  IF payout_amount <= 0 THEN
    RETURN 0;
  END IF;

  inv_period_s := COALESCE(inv_period_s, min_date::date, CURRENT_DATE);
  inv_period_e := COALESCE(inv_period_e, max_date::date, CURRENT_DATE);

  SELECT COALESCE(MAX(CAST(SUBSTRING(invoice_number FROM '[0-9]+$') AS integer)), 0) + 1
  INTO next_num
  FROM public.restaurant_invoices
  WHERE restaurant_id = p_restaurant_id
    AND COALESCE(invoice_type, 'payout') = 'payout';

  INSERT INTO public.restaurant_invoices (
    restaurant_id,
    period_start,
    period_end,
    amount_ht,
    amount_tva,
    amount_ttc,
    status,
    invoice_number,
    due_at,
    invoice_type
  )
  VALUES (
    p_restaurant_id,
    inv_period_s,
    inv_period_e,
    ROUND(payout_amount / (1 + tva_rate), 2),
    ROUND(payout_amount - payout_amount / (1 + tva_rate), 2),
    payout_amount,
    'pending',
    'FAC-' || TO_CHAR(CURRENT_DATE, 'YYYYMM') || '-' || LPAD(next_num::text, 4, '0'),
    (CURRENT_DATE + interval '30 days')::timestamptz,
    'payout'
  )
  RETURNING id INTO inv_id;

  UPDATE public.orders o
  SET restaurant_invoice_id = inv_id
  WHERE o.restaurant_id = p_restaurant_id
    AND o.restaurant_invoice_id IS NULL
    AND lower(COALESCE(o.status, '')) NOT IN ('cancelled', 'refused', 'payment_failed', 'pending')
    AND lower(COALESCE(o.payment_status, '')) IN ('paid', 'captured')
    AND GREATEST(
      COALESCE(o.total_amount, 0)
      + COALESCE((o.metadata ->> 'points_discount_amount')::numeric, (o.metadata ->> 'points_discount')::numeric, 0)
      - COALESCE(o.refunded_amount_chf, 0),
      0
    ) > 0
    AND (
      NOT v_has_month
      OR (
        o.created_at >= inv_period_s::timestamptz
        AND o.created_at < (inv_period_e + 1)::timestamptz
      )
    );

  UPDATE public.reservations r
  SET restaurant_invoice_id = inv_id
  WHERE r.restaurant_id = p_restaurant_id
    AND r.restaurant_invoice_id IS NULL
    AND lower(COALESCE(r.status, '')) NOT IN ('cancelled', 'no_show', 'pending')
    AND COALESCE(r.total_amount, 0) > 0
    AND GREATEST(COALESCE(r.total_amount, 0) - COALESCE(r.refunded_amount_chf, 0), 0) > 0
    AND (
      NOT v_has_month
      OR (
        COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) >= inv_period_s::timestamptz
        AND COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) < (inv_period_e + 1)::timestamptz
      )
    );

  RETURN 1;
END;
$function$;

CREATE OR REPLACE FUNCTION public.generate_restaurant_payout_invoice(
  p_restaurant_id uuid,
  p_month date DEFAULT NULL::date
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
BEGIN
  RETURN public.generate_restaurant_payout_invoice(p_restaurant_id, p_month::text);
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, text) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, text) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, text) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, text) TO service_role;

REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, date) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.generate_restaurant_payout_invoice(uuid, date) TO service_role;

CREATE OR REPLACE FUNCTION public.generate_tok_payable_invoice(
  p_restaurant_id uuid,
  p_month date DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_target date := COALESCE(p_month, (date_trunc('month', now()) - interval '1 month')::date);
  v_period_s date := date_trunc('month', v_target)::date;
  v_period_e date := (v_period_s + interval '1 month - 1 day')::date;
  v_next_num integer;
  v_invoice_id uuid;
  v_item_count integer := 0;
  v_total_ttc numeric := 0;
BEGIN
  IF NOT (auth.role() = 'service_role' OR public.auth_is_admin()) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  DROP TABLE IF EXISTS pg_temp.tmp_payable_invoice_items;
  CREATE TEMP TABLE pg_temp.tmp_payable_invoice_items (
    item_kind text NOT NULL,
    source_table text,
    source_id uuid,
    source_label text,
    occurred_at timestamptz NOT NULL,
    quantity numeric NOT NULL DEFAULT 1,
    unit_amount numeric NOT NULL DEFAULT 0,
    base_amount numeric NOT NULL DEFAULT 0,
    rate_label text,
    rate_value numeric,
    amount_ht numeric NOT NULL DEFAULT 0,
    amount_tva numeric NOT NULL DEFAULT 0,
    amount_ttc numeric NOT NULL DEFAULT 0,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb
  ) ON COMMIT DROP;

  INSERT INTO pg_temp.tmp_payable_invoice_items (
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  )
  SELECT
    'order_commission',
    'orders',
    o.id,
    CONCAT(
      'Commande ',
      COALESCE(NULLIF(trim(COALESCE(o.order_number, '')), ''), '#' || left(o.id::text, 8))
    ),
    o.created_at,
    1,
    ROUND(a.net_amount, 2),
    ROUND(a.net_amount, 2),
    '10%',
    0.10,
    ROUND(a.net_amount * 0.10, 2),
    0,
    ROUND(a.net_amount * 0.10, 2),
    jsonb_build_object(
      'order_number', o.order_number,
      'payment_status', o.payment_status,
      'status', o.status,
      'refunded_amount_chf', COALESCE(o.refunded_amount_chf, 0)
    )
  FROM public.orders o
  CROSS JOIN LATERAL (
    SELECT GREATEST(
      COALESCE(o.total_amount, 0)
      + COALESCE((o.metadata ->> 'points_discount_amount')::numeric, (o.metadata ->> 'points_discount')::numeric, 0)
      - COALESCE(o.refunded_amount_chf, 0),
      0
    ) AS net_amount
  ) a
  WHERE o.restaurant_id = p_restaurant_id
    AND o.created_at >= v_period_s::timestamptz
    AND o.created_at < (v_period_e + 1)::timestamptz
    AND lower(COALESCE(o.payment_status, '')) IN ('paid', 'captured')
    AND lower(COALESCE(o.status, '')) NOT IN ('cancelled', 'payment_failed', 'refused', 'pending', 'pending_payment')
    AND a.net_amount > 0
    AND NOT EXISTS (
      SELECT 1
      FROM public.restaurant_invoice_line_items li
      WHERE li.source_table = 'orders'
        AND li.source_id = o.id
        AND li.item_kind = 'order_commission'
    );

  INSERT INTO pg_temp.tmp_payable_invoice_items (
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  )
  SELECT
    'reservation_commission',
    'reservations',
    r.id,
    CASE
      WHEN NULLIF(trim(COALESCE(r.order_reference, '')), '') IS NOT NULL
        THEN CONCAT('Reservation ', r.order_reference)
      ELSE CONCAT('Reservation #', left(r.id::text, 8))
    END,
    COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz, now()),
    1,
    ROUND(a.net_amount, 2),
    ROUND(a.net_amount, 2),
    '10%',
    0.10,
    ROUND(a.net_amount * 0.10, 2),
    0,
    ROUND(a.net_amount * 0.10, 2),
    jsonb_build_object(
      'feature', r.feature,
      'status', r.status,
      'refunded_amount_chf', COALESCE(r.refunded_amount_chf, 0)
    )
  FROM public.reservations r
  CROSS JOIN LATERAL (
    SELECT GREATEST(
      COALESCE(r.total_amount, 0) - COALESCE(r.refunded_amount_chf, 0),
      0
    ) AS net_amount
  ) a
  WHERE r.restaurant_id = p_restaurant_id
    AND COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) >= v_period_s::timestamptz
    AND COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) < (v_period_e + 1)::timestamptz
    AND COALESCE(r.total_amount, 0) > 0
    AND lower(COALESCE(r.status, '')) NOT IN ('cancelled', 'no_show', 'pending')
    AND a.net_amount > 0
    AND NOT EXISTS (
      SELECT 1
      FROM public.restaurant_invoice_line_items li
      WHERE li.source_table = 'reservations'
        AND li.source_id = r.id
        AND li.item_kind = 'reservation_commission'
    );

  INSERT INTO pg_temp.tmp_payable_invoice_items (
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  )
  SELECT
    'reservation_fee',
    'reservations',
    r.id,
    CASE
      WHEN NULLIF(trim(COALESCE(r.order_reference, '')), '') IS NOT NULL
        THEN CONCAT('Reservation ', r.order_reference)
      ELSE CONCAT('Reservation #', left(r.id::text, 8))
    END,
    COALESCE(r.confirmed_at, r.created_at, r.updated_at, now()),
    1,
    ROUND(COALESCE(r.billing_fee_chf, 0), 2),
    ROUND(COALESCE(r.billing_fee_chf, 0), 2),
    CONCAT(ROUND(COALESCE(r.billing_fee_chf, 0), 2), ' CHF / reservation'),
    NULL,
    ROUND(COALESCE(r.billing_fee_chf, 0), 2),
    0,
    ROUND(COALESCE(r.billing_fee_chf, 0), 2),
    jsonb_build_object(
      'status', r.status,
      'cancelled_by', r.cancelled_by,
      'feature', r.feature
    )
  FROM public.reservations r
  WHERE r.restaurant_id = p_restaurant_id
    AND r.confirmed_at IS NOT NULL
    AND r.confirmed_at::date BETWEEN v_period_s AND v_period_e
    AND r.reservation_fee_invoice_id IS NULL
    AND (r.cancelled_by IS NULL OR r.cancelled_by NOT IN ('customer', 'admin'))
    AND NOT EXISTS (
      SELECT 1
      FROM public.restaurant_invoice_line_items li
      WHERE li.source_table = 'reservations'
        AND li.source_id = r.id
        AND li.item_kind = 'reservation_fee'
    );

  INSERT INTO pg_temp.tmp_payable_invoice_items (
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  )
  SELECT
    'campaign_payment',
    'ad_campaigns',
    c.id,
    COALESCE(NULLIF(trim(COALESCE(c.title, '')), ''), 'Campagne publicitaire'),
    COALESCE(c.created_at, now()),
    1,
    ROUND(
      CASE
        WHEN COALESCE(c.paid_amount, 0) > 0 THEN c.paid_amount
        ELSE COALESCE(c.total_budget, 0)
      END,
      2
    ),
    ROUND(
      CASE
        WHEN COALESCE(c.paid_amount, 0) > 0 THEN c.paid_amount
        ELSE COALESCE(c.total_budget, 0)
      END,
      2
    ),
    'Montant facture',
    NULL,
    ROUND(
      CASE
        WHEN COALESCE(c.paid_amount, 0) > 0 THEN c.paid_amount
        ELSE COALESCE(c.total_budget, 0)
      END,
      2
    ),
    0,
    ROUND(
      CASE
        WHEN COALESCE(c.paid_amount, 0) > 0 THEN c.paid_amount
        ELSE COALESCE(c.total_budget, 0)
      END,
      2
    ),
    jsonb_build_object(
      'payment_status', c.payment_status,
      'status', c.status
    )
  FROM public.ad_campaigns c
  WHERE c.restaurant_id = p_restaurant_id
    AND COALESCE(c.payment_status, 'unpaid') = 'paid'
    AND c.created_at >= v_period_s::timestamptz
    AND c.created_at < (v_period_e + 1)::timestamptz
    AND NOT EXISTS (
      SELECT 1
      FROM public.restaurant_invoice_line_items li
      WHERE li.source_table = 'ad_campaigns'
        AND li.source_id = c.id
        AND li.item_kind = 'campaign_payment'
    );

  SELECT COUNT(*), COALESCE(SUM(amount_ttc), 0)
    INTO v_item_count, v_total_ttc
  FROM pg_temp.tmp_payable_invoice_items;

  IF v_item_count = 0 OR v_total_ttc <= 0 THEN
    RETURN NULL;
  END IF;

  SELECT COALESCE(MAX(CAST(SUBSTRING(invoice_number FROM '[0-9]+$') AS integer)), 0) + 1
    INTO v_next_num
  FROM public.restaurant_invoices
  WHERE restaurant_id = p_restaurant_id
    AND invoice_type IN ('payable', 'reservation_fees');

  INSERT INTO public.restaurant_invoices (
    restaurant_id,
    period_start,
    period_end,
    amount_ht,
    amount_tva,
    amount_ttc,
    status,
    invoice_number,
    due_at,
    invoice_type
  )
  VALUES (
    p_restaurant_id,
    v_period_s,
    v_period_e,
    ROUND(v_total_ttc, 2),
    0,
    ROUND(v_total_ttc, 2),
    'pending',
    'TOK-' || TO_CHAR(v_period_s, 'YYYYMM') || '-' || LPAD(v_next_num::text, 4, '0'),
    (v_period_e + interval '30 days')::timestamptz,
    'payable'
  )
  RETURNING id INTO v_invoice_id;

  INSERT INTO public.restaurant_invoice_line_items (
    invoice_id,
    restaurant_id,
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  )
  SELECT
    v_invoice_id,
    p_restaurant_id,
    item_kind,
    source_table,
    source_id,
    source_label,
    occurred_at,
    quantity,
    unit_amount,
    base_amount,
    rate_label,
    rate_value,
    amount_ht,
    amount_tva,
    amount_ttc,
    metadata
  FROM pg_temp.tmp_payable_invoice_items
  ORDER BY occurred_at ASC, source_label ASC;

  UPDATE public.reservations
     SET reservation_fee_invoice_id = v_invoice_id,
         updated_at = now()
   WHERE id IN (
     SELECT source_id
     FROM pg_temp.tmp_payable_invoice_items
     WHERE item_kind = 'reservation_fee'
       AND source_id IS NOT NULL
   );

  RETURN v_invoice_id;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoice(uuid, date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoice(uuid, date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoice(uuid, date) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.generate_tok_payable_invoice(uuid, date) TO service_role;

CREATE OR REPLACE FUNCTION public.generate_tok_payable_invoices_all(
  p_month date DEFAULT NULL
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_count integer := 0;
  v_target date := COALESCE(p_month, (date_trunc('month', now()) - interval '1 month')::date);
  v_period_s date := date_trunc('month', v_target)::date;
  v_period_e date := (v_period_s + interval '1 month - 1 day')::date;
  v_restaurant uuid;
BEGIN
  IF NOT (auth.role() = 'service_role' OR public.auth_is_admin()) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  FOR v_restaurant IN
    SELECT DISTINCT restaurant_id
    FROM (
      SELECT o.restaurant_id
      FROM public.orders o
      WHERE o.created_at >= v_period_s::timestamptz
        AND o.created_at < (v_period_e + 1)::timestamptz
        AND lower(COALESCE(o.payment_status, '')) IN ('paid', 'captured')
        AND lower(COALESCE(o.status, '')) NOT IN ('cancelled', 'payment_failed', 'refused', 'pending', 'pending_payment')
        AND GREATEST(
          COALESCE(o.total_amount, 0)
          + COALESCE((o.metadata ->> 'points_discount_amount')::numeric, (o.metadata ->> 'points_discount')::numeric, 0)
          - COALESCE(o.refunded_amount_chf, 0),
          0
        ) > 0
        AND NOT EXISTS (
          SELECT 1
          FROM public.restaurant_invoice_line_items li
          WHERE li.source_table = 'orders'
            AND li.source_id = o.id
            AND li.item_kind = 'order_commission'
        )
      UNION
      SELECT r.restaurant_id
      FROM public.reservations r
      WHERE COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) >= v_period_s::timestamptz
        AND COALESCE(r.confirmed_at, r.created_at, r.updated_at, r.date::timestamptz) < (v_period_e + 1)::timestamptz
        AND COALESCE(r.total_amount, 0) > 0
        AND lower(COALESCE(r.status, '')) NOT IN ('cancelled', 'no_show', 'pending')
        AND GREATEST(COALESCE(r.total_amount, 0) - COALESCE(r.refunded_amount_chf, 0), 0) > 0
        AND NOT EXISTS (
          SELECT 1
          FROM public.restaurant_invoice_line_items li
          WHERE li.source_table = 'reservations'
            AND li.source_id = r.id
            AND li.item_kind = 'reservation_commission'
        )
      UNION
      SELECT r.restaurant_id
      FROM public.reservations r
      WHERE r.confirmed_at IS NOT NULL
        AND r.confirmed_at::date BETWEEN v_period_s AND v_period_e
        AND r.reservation_fee_invoice_id IS NULL
        AND (r.cancelled_by IS NULL OR r.cancelled_by NOT IN ('customer', 'admin'))
        AND NOT EXISTS (
          SELECT 1
          FROM public.restaurant_invoice_line_items li
          WHERE li.source_table = 'reservations'
            AND li.source_id = r.id
            AND li.item_kind = 'reservation_fee'
        )
      UNION
      SELECT c.restaurant_id
      FROM public.ad_campaigns c
      WHERE COALESCE(c.payment_status, 'unpaid') = 'paid'
        AND c.created_at >= v_period_s::timestamptz
        AND c.created_at < (v_period_e + 1)::timestamptz
        AND NOT EXISTS (
          SELECT 1
          FROM public.restaurant_invoice_line_items li
          WHERE li.source_table = 'ad_campaigns'
            AND li.source_id = c.id
            AND li.item_kind = 'campaign_payment'
        )
    ) AS billable_restaurants
  LOOP
    IF public.generate_tok_payable_invoice(v_restaurant, v_target) IS NOT NULL THEN
      v_count := v_count + 1;
    END IF;
  END LOOP;

  RETURN v_count;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoices_all(date) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoices_all(date) FROM anon;
REVOKE EXECUTE ON FUNCTION public.generate_tok_payable_invoices_all(date) FROM authenticated;
GRANT EXECUTE ON FUNCTION public.generate_tok_payable_invoices_all(date) TO service_role;

CREATE OR REPLACE FUNCTION public.get_payout_invoice_lines(
  p_invoice_id uuid
)
RETURNS TABLE (
  line_id uuid,
  line_type text,
  source text,
  reference text,
  label text,
  occurred_at timestamptz,
  gross_amount numeric,
  rate_applied numeric,
  invoiced_amount numeric
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $function$
DECLARE
  v_invoice public.restaurant_invoices%ROWTYPE;
BEGIN
  SELECT *
    INTO v_invoice
  FROM public.restaurant_invoices
  WHERE id = p_invoice_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'invoice_not_found';
  END IF;

  IF COALESCE(v_invoice.invoice_type, 'payout') <> 'payout' THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  IF NOT (
    auth.role() = 'service_role'
    OR public.auth_is_admin()
    OR public.auth_owns_restaurant(v_invoice.restaurant_id)
  ) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;

  RETURN QUERY
  WITH order_lines AS (
    SELECT
      o.id AS line_id,
      'order'::text AS line_type,
      CASE
        WHEN n.feature_norm IN (
          public.normalize_search_text('ventes-flash'),
          public.normalize_search_text('ventes_flash'),
          public.normalize_search_text('flash-sale'),
          public.normalize_search_text('flash_sale')
        )
          OR public.is_truthy_text(o.metadata ->> 'has_flash_sale')
          OR public.is_truthy_text(o.metadata ->> 'is_flash_sale')
          OR NULLIF(trim(COALESCE(o.metadata ->> 'flash_sale_id', '')), '') IS NOT NULL
          OR oi.has_flash_sale_fallback
          THEN 'flash_sales'
        WHEN n.feature_norm IN (
          public.normalize_search_text('anti-gaspi'),
          public.normalize_search_text('anti_gaspi'),
          public.normalize_search_text('anti-waste'),
          public.normalize_search_text('anti_waste'),
          public.normalize_search_text('zero-gaspi'),
          public.normalize_search_text('zero_gaspi')
        )
          OR public.is_truthy_text(o.metadata ->> 'has_anti_gaspi')
          OR public.is_truthy_text(o.metadata ->> 'is_anti_waste')
          OR NULLIF(trim(COALESCE(o.metadata ->> 'anti_waste_offer_id', '')), '') IS NOT NULL
          OR oi.has_anti_gaspi_fallback
          THEN 'anti_gaspi'
        WHEN n.feature_norm IN (
          public.normalize_search_text('chefs-table'),
          public.normalize_search_text('chefs_table'),
          public.normalize_search_text('table-chef'),
          public.normalize_search_text('table_chef')
        )
          OR public.is_truthy_text(o.metadata ->> 'is_chefs_table')
          OR NULLIF(trim(COALESCE(o.metadata ->> 'chefs_table_id', '')), '') IS NOT NULL
          THEN 'chefs_table'
        WHEN n.feature_norm IN (public.normalize_search_text('zero-attente'), public.normalize_search_text('zero_attente'))
          THEN 'zero_attente'
        ELSE 'orders'
      END::text AS source,
      COALESCE(
        NULLIF(trim(COALESCE(o.order_number, '')), ''),
        left(o.id::text, 8)
      )::text AS reference,
      CONCAT(
        'Commande ',
        COALESCE(
          NULLIF(trim(COALESCE(o.order_number, '')), ''),
          '#' || left(o.id::text, 8)
        )
      )::text AS label,
      o.created_at AS occurred_at,
      ROUND(a.net_amount, 2)::numeric AS gross_amount,
      0.90::numeric AS rate_applied,
      ROUND(a.net_amount * 0.90, 2)::numeric AS invoiced_amount
    FROM public.orders o
    CROSS JOIN LATERAL (
      SELECT
        public.normalize_search_text(COALESCE(o.metadata ->> 'feature', '')) AS feature_norm
    ) AS n
    CROSS JOIN LATERAL (
      SELECT GREATEST(
        COALESCE(o.total_amount, 0)
        + COALESCE((o.metadata ->> 'points_discount_amount')::numeric, (o.metadata ->> 'points_discount')::numeric, 0)
        - COALESCE(o.refunded_amount_chf, 0),
        0
      ) AS net_amount
    ) AS a
    CROSS JOIN LATERAL (
      SELECT
        EXISTS (
          SELECT 1
          FROM public.order_items oi
          WHERE oi.order_id = o.id
            AND (
              oi.anti_waste_offer_id IS NOT NULL
              OR NULLIF(trim(COALESCE(oi.metadata ->> 'flash_sale_id', '')), '') IS NOT NULL
              OR NULLIF(trim(COALESCE(oi.metadata ->> 'anti_waste_offer_id', '')), '') IS NOT NULL
              OR public.is_truthy_text(oi.metadata ->> 'is_anti_waste')
              OR public.is_truthy_text(oi.metadata ->> 'is_flash_sale')
            )
        ) AS has_anti_gaspi_fallback,
        EXISTS (
          SELECT 1
          FROM public.order_items oi
          WHERE oi.order_id = o.id
            AND (
              NULLIF(trim(COALESCE(oi.metadata ->> 'flash_sale_id', '')), '') IS NOT NULL
              OR public.is_truthy_text(oi.metadata ->> 'is_flash_sale')
            )
        ) AS has_flash_sale_fallback
    ) AS oi
    WHERE o.restaurant_invoice_id = p_invoice_id
      AND a.net_amount > 0
  ),
  reservation_lines AS (
    SELECT
      r.id AS line_id,
      'reservation'::text AS line_type,
      CASE
        WHEN n.feature_norm IN (public.normalize_search_text('zero-attente'), public.normalize_search_text('zero_attente'))
          THEN 'zero_attente'
        WHEN n.feature_norm IN (
          public.normalize_search_text('chefs-table'),
          public.normalize_search_text('chefs_table'),
          public.normalize_search_text('table-chef'),
          public.normalize_search_text('table_chef')
        )
          THEN 'chefs_table'
        WHEN n.feature_norm IN (
          public.normalize_search_text('ventes-flash'),
          public.normalize_search_text('ventes_flash'),
          public.normalize_search_text('flash-sale'),
          public.normalize_search_text('flash_sale')
        )
          THEN 'flash_sales'
        WHEN n.feature_norm IN (
          public.normalize_search_text('anti-gaspi'),
          public.normalize_search_text('anti_gaspi'),
          public.normalize_search_text('anti-waste'),
          public.normalize_search_text('anti_waste'),
          public.normalize_search_text('zero-gaspi'),
          public.normalize_search_text('zero_gaspi')
        )
          THEN 'anti_gaspi'
        ELSE 'other'
      END::text AS source,
      COALESCE(
        NULLIF(trim(COALESCE(r.order_reference, '')), ''),
        left(r.id::text, 8)
      )::text AS reference,
      CASE
        WHEN n.feature_norm IN (public.normalize_search_text('zero-attente'), public.normalize_search_text('zero_attente'))
          THEN 'Reservation Zero Attente'
        WHEN n.feature_norm IN (
          public.normalize_search_text('chefs-table'),
          public.normalize_search_text('chefs_table'),
          public.normalize_search_text('table-chef'),
          public.normalize_search_text('table_chef')
        )
          THEN 'Reservation Chef''s Table'
        WHEN n.feature_norm IN (
          public.normalize_search_text('ventes-flash'),
          public.normalize_search_text('ventes_flash'),
          public.normalize_search_text('flash-sale'),
          public.normalize_search_text('flash_sale')
        )
          THEN 'Reservation Vente flash'
        WHEN n.feature_norm IN (
          public.normalize_search_text('anti-gaspi'),
          public.normalize_search_text('anti_gaspi'),
          public.normalize_search_text('anti-waste'),
          public.normalize_search_text('anti_waste'),
          public.normalize_search_text('zero-gaspi'),
          public.normalize_search_text('zero_gaspi')
        )
          THEN 'Reservation Anti-gaspi'
        ELSE 'Reservation'
      END::text AS label,
      COALESCE(r.confirmed_at, r.created_at, r.updated_at) AS occurred_at,
      ROUND(a.net_amount, 2)::numeric AS gross_amount,
      0.90::numeric AS rate_applied,
      ROUND(a.net_amount * 0.90, 2)::numeric AS invoiced_amount
    FROM public.reservations r
    CROSS JOIN LATERAL (
      SELECT public.normalize_search_text(COALESCE(r.feature, r.metadata ->> 'feature')) AS feature_norm
    ) AS n
    CROSS JOIN LATERAL (
      SELECT GREATEST(
        COALESCE(r.total_amount, 0) - COALESCE(r.refunded_amount_chf, 0),
        0
      ) AS net_amount
    ) AS a
    WHERE r.restaurant_invoice_id = p_invoice_id
      AND a.net_amount > 0
  )
  SELECT
    x.line_id,
    x.line_type,
    x.source,
    x.reference,
    x.label,
    x.occurred_at,
    x.gross_amount,
    x.rate_applied,
    x.invoiced_amount
  FROM (
    SELECT * FROM order_lines
    UNION ALL
    SELECT * FROM reservation_lines
  ) AS x
  ORDER BY x.occurred_at ASC, x.line_type ASC, x.line_id ASC;
END;
$function$;

REVOKE EXECUTE ON FUNCTION public.get_payout_invoice_lines(uuid) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.get_payout_invoice_lines(uuid) FROM anon;
GRANT EXECUTE ON FUNCTION public.get_payout_invoice_lines(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_payout_invoice_lines(uuid) TO service_role;

NOTIFY pgrst, 'reload schema';
