-- Durable, append-only restaurant onboarding lifecycle. Existing business tables
-- remain authoritative for their domain; this journal makes every cross-system
-- transition explicit, idempotent and support-auditable.
CREATE TABLE IF NOT EXISTS public.restaurant_onboarding_state_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  signup_application_id uuid NOT NULL REFERENCES public.signup_applications(id) ON DELETE RESTRICT,
  restaurant_id uuid REFERENCES public.restaurants(id) ON DELETE RESTRICT,
  payment_attempt_id uuid REFERENCES public.payment_attempts(id) ON DELETE RESTRICT,
  state text NOT NULL CHECK (state IN (
    'application_created', 'email_confirmed', 'configuration_allowed',
    'stripe_session_created', 'payment_method_saved', 'browser_return_received',
    'webhook_received', 'recovery_required', 'admin_approved'
  )),
  idempotency_key text NOT NULL CHECK (length(btrim(idempotency_key)) BETWEEN 1 AND 255),
  source text NOT NULL CHECK (length(btrim(source)) BETWEEN 1 AND 80),
  stripe_event_id text,
  actor_user_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (signup_application_id, state, idempotency_key)
);

CREATE INDEX IF NOT EXISTS idx_restaurant_onboarding_state_events_application_time
  ON public.restaurant_onboarding_state_events (signup_application_id, occurred_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS idx_restaurant_onboarding_state_events_restaurant_time
  ON public.restaurant_onboarding_state_events (restaurant_id, occurred_at DESC)
  WHERE restaurant_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS ux_restaurant_onboarding_state_events_stripe_event_state
  ON public.restaurant_onboarding_state_events (stripe_event_id, state)
  WHERE stripe_event_id IS NOT NULL;

ALTER TABLE public.restaurant_onboarding_state_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_onboarding_state_events FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS restaurant_onboarding_state_events_owner_read
  ON public.restaurant_onboarding_state_events;
CREATE POLICY restaurant_onboarding_state_events_owner_read
  ON public.restaurant_onboarding_state_events FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.signup_applications application
      WHERE application.id = signup_application_id
        AND application.user_id = (SELECT auth.uid())
    )
    OR (restaurant_id IS NOT NULL AND public.auth_owns_restaurant(restaurant_id))
    OR public.has_role((SELECT auth.uid()), 'admin'::public.app_role)
  );

REVOKE ALL ON TABLE public.restaurant_onboarding_state_events FROM PUBLIC, anon, authenticated;
GRANT SELECT ON TABLE public.restaurant_onboarding_state_events TO authenticated;

CREATE OR REPLACE FUNCTION public.record_restaurant_onboarding_state(
  p_signup_application_id uuid,
  p_restaurant_id uuid,
  p_payment_attempt_id uuid,
  p_state text,
  p_idempotency_key text,
  p_source text,
  p_stripe_event_id text DEFAULT NULL,
  p_actor_user_id uuid DEFAULT NULL,
  p_metadata jsonb DEFAULT '{}'::jsonb
) RETURNS public.restaurant_onboarding_state_events
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE v_event public.restaurant_onboarding_state_events;
BEGIN
  INSERT INTO public.restaurant_onboarding_state_events (
    signup_application_id, restaurant_id, payment_attempt_id, state,
    idempotency_key, source, stripe_event_id, actor_user_id, metadata
  ) VALUES (
    p_signup_application_id, p_restaurant_id, p_payment_attempt_id, p_state,
    btrim(p_idempotency_key), btrim(p_source), p_stripe_event_id,
    p_actor_user_id, COALESCE(p_metadata, '{}'::jsonb)
  )
  ON CONFLICT (signup_application_id, state, idempotency_key)
  DO UPDATE SET metadata = public.restaurant_onboarding_state_events.metadata
  RETURNING * INTO v_event;
  RETURN v_event;
END;
$$;

REVOKE ALL ON FUNCTION public.record_restaurant_onboarding_state(uuid, uuid, uuid, text, text, text, text, uuid, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.record_restaurant_onboarding_state(uuid, uuid, uuid, text, text, text, text, uuid, jsonb)
  TO service_role;

COMMENT ON TABLE public.restaurant_onboarding_state_events IS
  'Append-only audited server journal for restaurant onboarding; writes are service-role only and idempotent.';
