-- Make daily slot spins retry-safe while preserving the existing three-attempt
-- Swiss-day limit. The Edge Function supplies request_id in p_metadata so a
-- lost HTTP response can be replayed without crediting a second attempt.

ALTER TABLE public.daily_slot_spins
  ADD COLUMN IF NOT EXISTS request_id uuid;

CREATE UNIQUE INDEX IF NOT EXISTS daily_slot_spins_user_request_uidx
  ON public.daily_slot_spins (user_id, request_id)
  WHERE request_id IS NOT NULL;

COMMENT ON COLUMN public.daily_slot_spins.request_id IS
  'Idempotency key generated by the client for one logical slot spin.';

CREATE OR REPLACE FUNCTION public.record_daily_slot_spin(
  p_user_id uuid,
  p_spin_date date,
  p_symbols text[],
  p_reward_points integer,
  p_reward_label text,
  p_rng_nonce text,
  p_metadata jsonb DEFAULT '{}'::jsonb
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public', 'auth', 'pg_temp'
AS $function$
DECLARE
  v_spin public.daily_slot_spins%ROWTYPE;
  v_transaction_id uuid;
  v_total_points integer;
  v_attempt_count integer;
  v_attempt_number integer;
  v_max_attempts constant integer := 3;
  v_request_id uuid;
  v_request_id_text text := NULLIF(btrim(COALESCE(p_metadata->>'request_id', '')), '');
BEGIN
  IF COALESCE((SELECT auth.jwt()->>'role'), '') <> 'service_role' THEN
    RAISE EXCEPTION 'service_role_required' USING ERRCODE = '42501';
  END IF;

  IF p_user_id IS NULL THEN
    RAISE EXCEPTION 'user_id_required' USING ERRCODE = '22023';
  END IF;

  IF p_spin_date IS NULL THEN
    RAISE EXCEPTION 'spin_date_required' USING ERRCODE = '22023';
  END IF;

  IF cardinality(p_symbols) <> 3 THEN
    RAISE EXCEPTION 'three_symbols_required' USING ERRCODE = '22023';
  END IF;

  IF NOT (
    p_symbols <@
    ARRAY['tok_suisse', 'fork', 'chef', 'courier', 'logo', 'miamz']::text[]
  ) THEN
    RAISE EXCEPTION 'invalid_slot_symbol' USING ERRCODE = '22023';
  END IF;

  IF p_reward_points NOT IN (
    3, 4, 6, 8, 10, 12, 16, 18, 20, 24, 25, 30, 40, 45, 60, 100
  ) THEN
    RAISE EXCEPTION 'invalid_reward_points' USING ERRCODE = '22023';
  END IF;

  IF NULLIF(btrim(COALESCE(p_reward_label, '')), '') IS NULL
     OR char_length(p_reward_label) > 160 THEN
    RAISE EXCEPTION 'invalid_reward_label' USING ERRCODE = '22023';
  END IF;

  IF NULLIF(btrim(COALESCE(p_rng_nonce, '')), '') IS NULL THEN
    RAISE EXCEPTION 'rng_nonce_required' USING ERRCODE = '22023';
  END IF;

  IF v_request_id_text IS NULL THEN
    -- Backward compatibility for an old frontend during a rolling deploy.
    v_request_id := gen_random_uuid();
  ELSE
    BEGIN
      v_request_id := v_request_id_text::uuid;
    EXCEPTION
      WHEN invalid_text_representation THEN
        RAISE EXCEPTION 'invalid_request_id' USING ERRCODE = '22023';
    END;
  END IF;

  -- One lock serializes all attempts for a user and Swiss day. It also makes a
  -- concurrent retry wait for, then observe, the first committed result.
  PERFORM pg_advisory_xact_lock(
    hashtextextended(p_user_id::text || ':' || p_spin_date::text, 0)
  );

  SELECT *
  INTO v_spin
  FROM public.daily_slot_spins
  WHERE user_id = p_user_id
    AND request_id = v_request_id
  LIMIT 1;

  IF FOUND THEN
    SELECT count(*)
    INTO v_attempt_count
    FROM public.daily_slot_spins
    WHERE user_id = p_user_id
      AND spin_date = p_spin_date;

    SELECT COALESCE(loyalty_points, 0)
    INTO v_total_points
    FROM public.profiles
    WHERE user_id = p_user_id;

    RETURN jsonb_build_object(
      'ok', true,
      'already_claimed', false,
      'idempotent_replay', true,
      'attempts_used', v_attempt_count,
      'attempts_remaining', GREATEST(v_max_attempts - v_attempt_count, 0),
      'max_attempts', v_max_attempts,
      'spin', jsonb_build_object(
        'id', v_spin.id,
        'request_id', v_spin.request_id,
        'spin_date', v_spin.spin_date,
        'attempt_number', v_spin.attempt_number,
        'symbols', v_spin.symbols,
        'reward_points', v_spin.reward_points,
        'reward_label', v_spin.reward_label,
        'created_at', v_spin.created_at
      ),
      'total_loyalty_points', COALESCE(v_total_points, 0)
    );
  END IF;

  SELECT count(*)
  INTO v_attempt_count
  FROM public.daily_slot_spins
  WHERE user_id = p_user_id
    AND spin_date = p_spin_date;

  IF v_attempt_count >= v_max_attempts THEN
    SELECT *
    INTO v_spin
    FROM public.daily_slot_spins
    WHERE user_id = p_user_id
      AND spin_date = p_spin_date
    ORDER BY attempt_number DESC, created_at DESC
    LIMIT 1;

    SELECT COALESCE(loyalty_points, 0)
    INTO v_total_points
    FROM public.profiles
    WHERE user_id = p_user_id;

    RETURN jsonb_build_object(
      'ok', true,
      'already_claimed', true,
      'idempotent_replay', false,
      'attempts_used', v_attempt_count,
      'attempts_remaining', 0,
      'max_attempts', v_max_attempts,
      'spin', jsonb_build_object(
        'id', v_spin.id,
        'request_id', v_spin.request_id,
        'spin_date', v_spin.spin_date,
        'attempt_number', v_spin.attempt_number,
        'symbols', v_spin.symbols,
        'reward_points', v_spin.reward_points,
        'reward_label', v_spin.reward_label,
        'created_at', v_spin.created_at
      ),
      'total_loyalty_points', COALESCE(v_total_points, 0)
    );
  END IF;

  v_attempt_number := v_attempt_count + 1;

  INSERT INTO public.daily_slot_spins (
    user_id,
    request_id,
    spin_date,
    attempt_number,
    symbols,
    reward_points,
    reward_label,
    rng_nonce,
    metadata
  )
  VALUES (
    p_user_id,
    v_request_id,
    p_spin_date,
    v_attempt_number,
    p_symbols,
    p_reward_points,
    btrim(p_reward_label),
    btrim(p_rng_nonce),
    COALESCE(p_metadata, '{}'::jsonb) || jsonb_build_object(
      'request_id', v_request_id,
      'attempt_number', v_attempt_number,
      'max_attempts', v_max_attempts
    )
  )
  RETURNING * INTO v_spin;

  INSERT INTO public.loyalty_transactions (
    user_id,
    amount,
    transaction_type,
    description,
    metadata
  )
  VALUES (
    p_user_id,
    p_reward_points,
    'daily_slot_spin',
    'Gain machine à sous TOK',
    jsonb_build_object(
      'slot_spin_id', v_spin.id,
      'request_id', v_request_id,
      'spin_date', p_spin_date,
      'attempt_number', v_attempt_number,
      'max_attempts', v_max_attempts,
      'symbols', p_symbols,
      'reward_label', btrim(p_reward_label)
    ) || COALESCE(p_metadata, '{}'::jsonb)
  )
  RETURNING id INTO v_transaction_id;

  INSERT INTO public.profiles (user_id, loyalty_points)
  VALUES (p_user_id, p_reward_points)
  ON CONFLICT (user_id)
  DO UPDATE SET
    loyalty_points =
      COALESCE(public.profiles.loyalty_points, 0) + EXCLUDED.loyalty_points,
    updated_at = now();

  SELECT COALESCE(loyalty_points, 0)
  INTO v_total_points
  FROM public.profiles
  WHERE user_id = p_user_id;

  RETURN jsonb_build_object(
    'ok', true,
    'already_claimed', false,
    'idempotent_replay', false,
    'transaction_id', v_transaction_id,
    'attempts_used', v_attempt_number,
    'attempts_remaining', GREATEST(v_max_attempts - v_attempt_number, 0),
    'max_attempts', v_max_attempts,
    'spin', jsonb_build_object(
      'id', v_spin.id,
      'request_id', v_spin.request_id,
      'spin_date', v_spin.spin_date,
      'attempt_number', v_spin.attempt_number,
      'symbols', v_spin.symbols,
      'reward_points', v_spin.reward_points,
      'reward_label', v_spin.reward_label,
      'created_at', v_spin.created_at
    ),
    'total_loyalty_points', COALESCE(v_total_points, 0)
  );
END;
$function$;

REVOKE ALL ON FUNCTION public.record_daily_slot_spin(
  uuid, date, text[], integer, text, text, jsonb
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.record_daily_slot_spin(
  uuid, date, text[], integer, text, text, jsonb
) TO service_role;

NOTIFY pgrst, 'reload schema';

