-- Human-approved incident remediation for TOK.
-- Runtime writes are service-role only; authenticated administrators have read-only visibility.

CREATE TABLE IF NOT EXISTS public.ops_incidents (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  fingerprint text NOT NULL CHECK (char_length(fingerprint) BETWEEN 16 AND 128),
  source text NOT NULL CHECK (source IN ('edge_audit', 'github_actions', 'sentry', 'manual', 'external')),
  source_event_id text,
  severity text NOT NULL DEFAULT 'medium' CHECK (severity IN ('low', 'medium', 'high', 'critical')),
  status text NOT NULL DEFAULT 'detected' CHECK (
    status IN (
      'detected',
      'analyzing',
      'awaiting_approval',
      'approved',
      'repairing',
      'pr_open',
      'resolved',
      'rejected',
      'failed',
      'ignored'
    )
  ),
  title text NOT NULL CHECK (char_length(title) BETWEEN 3 AND 240),
  summary text NOT NULL DEFAULT '',
  probable_cause text,
  impact text,
  repair_plan jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(repair_plan) = 'object'),
  technical_details jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(technical_details) = 'object'),
  sanitized_context jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(sanitized_context) = 'object'),
  confidence numeric(5,4) CHECK (confidence IS NULL OR (confidence >= 0 AND confidence <= 1)),
  risk_level text CHECK (risk_level IS NULL OR risk_level IN ('low', 'medium', 'high', 'critical')),
  occurrence_count integer NOT NULL DEFAULT 1 CHECK (occurrence_count > 0),
  first_seen_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  approval_token_hash text CHECK (approval_token_hash IS NULL OR approval_token_hash ~ '^[0-9a-f]{64}$'),
  approval_expires_at timestamptz,
  approval_actor text,
  approved_at timestamptz,
  rejected_at timestamptz,
  decision_chat_id text,
  decision_message_id bigint,
  repair_context_token_hash text CHECK (repair_context_token_hash IS NULL OR repair_context_token_hash ~ '^[0-9a-f]{64}$'),
  repair_context_expires_at timestamptz,
  github_run_id bigint,
  github_branch text,
  github_pr_number integer,
  github_pr_url text,
  resolution_summary text,
  failure_reason text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.ops_incident_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  incident_id uuid NOT NULL REFERENCES public.ops_incidents(id) ON DELETE CASCADE,
  event_type text NOT NULL CHECK (char_length(event_type) BETWEEN 2 AND 80),
  actor text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(payload) = 'object'),
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ops_incidents_status_last_seen
  ON public.ops_incidents(status, last_seen_at DESC);

CREATE INDEX IF NOT EXISTS idx_ops_incidents_fingerprint_active
  ON public.ops_incidents(fingerprint, created_at DESC)
  WHERE status IN ('detected', 'analyzing', 'awaiting_approval', 'approved', 'repairing', 'pr_open');

CREATE INDEX IF NOT EXISTS idx_ops_incidents_source_event
  ON public.ops_incidents(source, source_event_id)
  WHERE source_event_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ops_incident_events_incident_created
  ON public.ops_incident_events(incident_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.ops_touch_incident_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = public
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_ops_incidents_updated_at ON public.ops_incidents;
CREATE TRIGGER trg_ops_incidents_updated_at
BEFORE UPDATE ON public.ops_incidents
FOR EACH ROW
EXECUTE FUNCTION public.ops_touch_incident_updated_at();

CREATE OR REPLACE FUNCTION public.ops_register_incident(
  p_fingerprint text,
  p_source text,
  p_source_event_id text,
  p_severity text,
  p_title text,
  p_summary text,
  p_technical_details jsonb DEFAULT '{}'::jsonb,
  p_sanitized_context jsonb DEFAULT '{}'::jsonb
)
RETURNS TABLE (
  incident_id uuid,
  created_new boolean,
  incident_status text
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_existing public.ops_incidents%ROWTYPE;
  v_incident_id uuid;
  v_status text;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required.' USING ERRCODE = '42501';
  END IF;

  IF p_fingerprint IS NULL OR char_length(trim(p_fingerprint)) NOT BETWEEN 16 AND 128 THEN
    RAISE EXCEPTION 'Invalid incident fingerprint.' USING ERRCODE = '22023';
  END IF;

  IF p_source NOT IN ('edge_audit', 'github_actions', 'sentry', 'manual', 'external') THEN
    RAISE EXCEPTION 'Invalid incident source.' USING ERRCODE = '22023';
  END IF;

  IF p_severity NOT IN ('low', 'medium', 'high', 'critical') THEN
    RAISE EXCEPTION 'Invalid incident severity.' USING ERRCODE = '22023';
  END IF;

  IF char_length(trim(COALESCE(p_title, ''))) < 3 THEN
    RAISE EXCEPTION 'Incident title is required.' USING ERRCODE = '22023';
  END IF;

  -- Serialise identical fingerprints so concurrent collectors cannot create duplicates.
  PERFORM pg_advisory_xact_lock(hashtext(p_fingerprint)::bigint);

  SELECT *
  INTO v_existing
  FROM public.ops_incidents
  WHERE fingerprint = p_fingerprint
    AND status IN ('detected', 'analyzing', 'awaiting_approval', 'approved', 'repairing', 'pr_open')
  ORDER BY created_at DESC
  LIMIT 1
  FOR UPDATE;

  IF FOUND THEN
    UPDATE public.ops_incidents
    SET source_event_id = COALESCE(NULLIF(p_source_event_id, ''), source_event_id),
        severity = CASE
          WHEN CASE p_severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            ELSE 1
          END > CASE severity
            WHEN 'critical' THEN 4
            WHEN 'high' THEN 3
            WHEN 'medium' THEN 2
            ELSE 1
          END
          THEN p_severity
          ELSE severity
        END,
        title = left(trim(p_title), 240),
        summary = left(COALESCE(p_summary, ''), 4000),
        technical_details = COALESCE(p_technical_details, '{}'::jsonb),
        sanitized_context = COALESCE(p_sanitized_context, '{}'::jsonb),
        occurrence_count = occurrence_count + 1,
        last_seen_at = now()
    WHERE id = v_existing.id
    RETURNING id, status INTO v_incident_id, v_status;

    INSERT INTO public.ops_incident_events (incident_id, event_type, actor, payload)
    VALUES (
      v_incident_id,
      'occurrence_deduplicated',
      'ops-incident-control',
      jsonb_build_object('source', p_source, 'source_event_id', p_source_event_id)
    );

    RETURN QUERY SELECT v_incident_id, false, v_status;
    RETURN;
  END IF;

  INSERT INTO public.ops_incidents (
    fingerprint,
    source,
    source_event_id,
    severity,
    status,
    title,
    summary,
    technical_details,
    sanitized_context
  )
  VALUES (
    trim(p_fingerprint),
    p_source,
    NULLIF(p_source_event_id, ''),
    p_severity,
    'detected',
    left(trim(p_title), 240),
    left(COALESCE(p_summary, ''), 4000),
    COALESCE(p_technical_details, '{}'::jsonb),
    COALESCE(p_sanitized_context, '{}'::jsonb)
  )
  RETURNING id, status INTO v_incident_id, v_status;

  INSERT INTO public.ops_incident_events (incident_id, event_type, actor, payload)
  VALUES (
    v_incident_id,
    'incident_detected',
    'ops-incident-control',
    jsonb_build_object('source', p_source, 'source_event_id', p_source_event_id)
  );

  RETURN QUERY SELECT v_incident_id, true, v_status;
END;
$$;

CREATE OR REPLACE FUNCTION public.ops_decide_incident(
  p_incident_id uuid,
  p_token_hash text,
  p_decision text,
  p_actor text
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth
AS $$
DECLARE
  v_incident public.ops_incidents%ROWTYPE;
  v_decision text := lower(trim(COALESCE(p_decision, '')));
  v_status text;
BEGIN
  IF COALESCE(auth.role(), '') <> 'service_role' THEN
    RAISE EXCEPTION 'Service role required.' USING ERRCODE = '42501';
  END IF;

  IF v_decision NOT IN ('approve', 'reject') THEN
    RAISE EXCEPTION 'Unsupported incident decision.' USING ERRCODE = '22023';
  END IF;

  SELECT *
  INTO v_incident
  FROM public.ops_incidents
  WHERE id = p_incident_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Incident not found.' USING ERRCODE = '22023';
  END IF;

  IF v_incident.status <> 'awaiting_approval' THEN
    RAISE EXCEPTION 'Incident is no longer awaiting approval.' USING ERRCODE = '55000';
  END IF;

  IF v_incident.approval_expires_at IS NULL OR v_incident.approval_expires_at <= now() THEN
    RAISE EXCEPTION 'Incident approval expired.' USING ERRCODE = '55000';
  END IF;

  IF v_incident.approval_token_hash IS NULL OR v_incident.approval_token_hash <> p_token_hash THEN
    RAISE EXCEPTION 'Invalid incident approval token.' USING ERRCODE = '42501';
  END IF;

  v_status := CASE WHEN v_decision = 'approve' THEN 'approved' ELSE 'rejected' END;

  UPDATE public.ops_incidents
  SET status = v_status,
      approval_actor = left(COALESCE(p_actor, 'telegram'), 240),
      approved_at = CASE WHEN v_decision = 'approve' THEN now() ELSE approved_at END,
      rejected_at = CASE WHEN v_decision = 'reject' THEN now() ELSE rejected_at END,
      approval_token_hash = NULL,
      approval_expires_at = NULL
  WHERE id = p_incident_id;

  INSERT INTO public.ops_incident_events (incident_id, event_type, actor, payload)
  VALUES (
    p_incident_id,
    CASE WHEN v_decision = 'approve' THEN 'repair_approved' ELSE 'repair_rejected' END,
    left(COALESCE(p_actor, 'telegram'), 240),
    jsonb_build_object('decision', v_decision)
  );

  RETURN jsonb_build_object(
    'incident_id', p_incident_id,
    'status', v_status,
    'decision', v_decision
  );
END;
$$;

ALTER TABLE public.ops_incidents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ops_incident_events ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS ops_incidents_admin_select ON public.ops_incidents;
CREATE POLICY ops_incidents_admin_select
  ON public.ops_incidents
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

DROP POLICY IF EXISTS ops_incident_events_admin_select ON public.ops_incident_events;
CREATE POLICY ops_incident_events_admin_select
  ON public.ops_incident_events
  FOR SELECT
  TO authenticated
  USING (public.auth_is_admin());

REVOKE ALL ON public.ops_incidents FROM anon, authenticated;
REVOKE ALL ON public.ops_incident_events FROM anon, authenticated;
GRANT SELECT ON public.ops_incidents TO authenticated;
GRANT SELECT ON public.ops_incident_events TO authenticated;
REVOKE ALL ON public.ops_incidents FROM service_role;
REVOKE ALL ON public.ops_incident_events FROM service_role;
GRANT SELECT, INSERT, UPDATE ON public.ops_incidents TO service_role;
GRANT SELECT, INSERT ON public.ops_incident_events TO service_role;
GRANT USAGE, SELECT ON SEQUENCE public.ops_incident_events_id_seq TO service_role;

REVOKE ALL ON FUNCTION public.ops_touch_incident_updated_at() FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops_touch_incident_updated_at() TO service_role;

REVOKE ALL ON FUNCTION public.ops_register_incident(text, text, text, text, text, text, jsonb, jsonb)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops_register_incident(text, text, text, text, text, text, jsonb, jsonb)
  TO service_role;

REVOKE ALL ON FUNCTION public.ops_decide_incident(uuid, text, text, text)
  FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.ops_decide_incident(uuid, text, text, text)
  TO service_role;

COMMENT ON TABLE public.ops_incidents IS
  'Human-approved incident queue. Context is sanitized before persistence; runtime writes use service_role only.';
COMMENT ON TABLE public.ops_incident_events IS
  'Append-only audit trail for detection, approval, Codex execution, PR creation, and resolution events.';
