// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from '@/lib/env';
import { readSupabasePublicEnv } from '@/lib/publicEnv';
import { authStorage } from './authStorage';
import {
  getCommercialDemoSupabase,
  isCommercialDemoFramePath,
} from './demoClient';

// Import the supabase client like this:
// import { getSupabase } from "@/integrations/supabase/client";

let productionSupabase: SupabaseClient<Database> | null = null;

export function getProductionSupabase(): SupabaseClient<Database> {
  if (productionSupabase) return productionSupabase;

  const { url, publishableKey } = readSupabasePublicEnv(
    {
      VITE_SUPABASE_URL: SUPABASE_URL,
      VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY,
    },
    "runtime",
  );

  productionSupabase = createClient<Database>(url, publishableKey, {
    auth: {
      storage: authStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: "pkce",
      detectSessionInUrl: false,
    },
  });

  return productionSupabase;
}

export function getSupabase(): SupabaseClient<Database> {
  if (
    typeof window !== "undefined"
    && isCommercialDemoFramePath(window.location.pathname)
  ) {
    return getCommercialDemoSupabase();
  }
  return getProductionSupabase();
}
