// This file is automatically generated. Do not edit it directly.
import { createClient, type SupabaseClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { SUPABASE_PUBLISHABLE_KEY, SUPABASE_URL } from '@/lib/env';
import { readSupabasePublicEnv } from '@/lib/publicEnv';
import { authStorage } from './authStorage';

// Import the supabase client like this:
// import { getSupabase } from "@/integrations/supabase/client";

let supabase: SupabaseClient<Database> | null = null;

export function getSupabase(): SupabaseClient<Database> {
  if (supabase) return supabase;

  const { url, publishableKey } = readSupabasePublicEnv(
    {
      VITE_SUPABASE_URL: SUPABASE_URL,
      VITE_SUPABASE_PUBLISHABLE_KEY: SUPABASE_PUBLISHABLE_KEY,
    },
    "runtime",
  );

  supabase = createClient<Database>(url, publishableKey, {
    auth: {
      storage: authStorage,
      persistSession: true,
      autoRefreshToken: true,
      flowType: "pkce",
      detectSessionInUrl: false,
    },
  });

  return supabase;
}
